-- Run this script once in Supabase Dashboard -> SQL Editor.
create table if not exists public.weather_plans (
  id bigint generated by default as identity primary key,
  city text not null,
  activity text not null,
  temperature_c numeric(5, 2) not null,
  humidity_pct integer not null check (humidity_pct between 0 and 100),
  wind_speed_mps numeric(5, 2) not null check (wind_speed_mps >= 0),
  suitability_score integer not null check (suitability_score between 0 and 100),
  rating text not null,
  created_at timestamptz not null default now()
);

alter table public.weather_plans enable row level security;

drop policy if exists "Allow anonymous plan inserts" on public.weather_plans;
drop policy if exists "Allow public plan inserts" on public.weather_plans;
create policy "Allow public plan inserts"
on public.weather_plans for insert
to public
with check (true);

drop policy if exists "Allow anonymous plan reads" on public.weather_plans;
drop policy if exists "Allow public plan reads" on public.weather_plans;
create policy "Allow public plan reads"
on public.weather_plans for select
to public
using (true);

grant usage on schema public to anon, authenticated;
grant select, insert on table public.weather_plans to anon, authenticated;
